### ISSUE TITLE
'@types/react-json-to-csv@latest' is not in the npm registry

### ISSUE THREAD

**Issue by jaydeep-punjani** [coston/react-json-to-csv#26]
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2freact-json-to-csv - Not found
npm ERR! 404 
npm ERR! 404  '@types/react-json-to-csv@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by coston** [comment]
@jaydeep-punjani, I do not have capacity to add types at the moment. A PR to add types would be appreciated! 🤝

**Comment by coston** [comment]
@jaydeep-punjani feel free to open a PR for this. Closing for now.
